version: '3.8'
services:
  webapp:
    build:
      context: .
      args:
        - buildVersion: 186-alpha
    extra_hosts:
        - "bigfit:192.168.1.139"
        - "unifit:192.168.1.7"
    ports:
        - "8888:8080"
        - "5005:5005"
